#!/bin/bash -e

ALL_BUILDS="protoc-all protoc prototool grpc-cli gen-grpc-gateway"
BUILDS=${BUILDS:-$ALL_BUILDS}
DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-namely}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}

DEBIAN_VERSION=${DEBIAN_VERSION:-bullseye}
GO_VERSION=${GO_VERSION:-1.19}
GRPC_VERSION=${GRPC_VERSION:-1.51}
GO_ENVOYPROXY_PGV_VERSION=${GO_ENVOYPROXY_PGV_VERSION:-0.9.1}
GO_MWITKOW_GPV_VERSION=${GO_MWITKOW_GPV_VERSION:-0.3.2}
GO_PROTOC_GEN_GO_VERSION=${GO_PROTOC_GEN_GO_VERSION:-v1.28.1}
GO_PROTOC_GEN_GO_GRPC_VERSION=${GO_PROTOC_GEN_GO_GRPC_VERSION:-v1.2.0}
GO_PROTOC_GEN_GO_TTRPC_VERSION=${GO_PROTOC_GEN_GO_TTRPC_VERSION:-v1.2.3}
BUILD_VERSION="${BUILD_VERSION:-local}"
VERSION="${VERSION:-${GRPC_VERSION}_${BUILD_VERSION}}"
